CPPFLAGS += `pkg-config libk4w2 --cflags`
LDFLAGS  += `pkg-config libk4w2 --libs-only-L`
LDLIBS   += `pkg-config libk4w2 --libs-only-l`

TARGETS += simple

all: $(TARGETS)
clean:
	$(RM) -f $(TARGETS) *.o *~
