all:
	@echo "usage: "
	@echo ""
	@echo " make -f Makefile.simple "
	@echo " make -f Makefile.opencv "
	@echo " make -f Makefile.opengl "
	@echo " make -f Makefile.liveview "
	@echo ""
clean:
	$(RM) -f $(TARGETS) *.o *~
